### ISSUE TITLE
Login and sign up page

### ISSUE THREAD

**Issue by shivshankar9** [Akshima-Ghai/OneEducationalWebsiteForAll#30]
Login and sign up page

**Comment by NikhilSharma03** [comment]
Working on that.

**Comment by sujith248** [comment]
So can I work on that too?

**Comment by urmi-256** [comment]
Can I work on this issue too? Will be creating a cool login and sign up page.

**Comment by TheArushiSingh** [comment]
I'm interested in working on that

**Comment by Akshima-Ghai** [comment]
ISSUE ASSIGNED TO @shivshankar9 and @NikhilSharma03  , try to complete it asap, you both can discuss with each other. If the UI made is not up to the mark, then the issue will be assigned to the next person. Issues are assigned on FCFB so try to check the issues update daily so that you can work on the issue you wish for. But still, we have a lot more issues, the contributors who haven't assigned any issues can ask for different issues.

**Comment by pranjay-poddar** [comment]
Please assign this task to me.

**Comment by Akshima-Ghai** [comment]
This task is already assigned , you can work on different issue
